### ISSUE TITLE
No repository persistence

### ISSUE THREAD

**Issue by oliveiraev** [Lucas-C/pre-commit-hooks-nodejs#1]
Im trying to use Dockerfile linter but, every time I run ```git commit``` it "installs" the repository again.

**Comment by Lucas-C** [comment]
Hello.

Thanks for reporting an issue !

Could you give me a little more details please ?
What OS & Python version are you using, and what is the content of your `.pre-commit-config.yaml` ?

**Comment by Lucas-C** [comment]
Also, it may that you `pre-commit` version is too old (very likely if you are using Cygwin).
Could run the following please ?

    pre-commit --version

**Comment by Lucas-C** [comment]
@oliveiraev : Did you solve your problem ?

**Comment by oliveiraev** [comment]
Could be an issue with filesystem or network. I'll close for now and, if I can reproduce it, I file it again.

Thank you.
